theme: jekyll-theme-modernist
title: Mustafa Gumustas
description: Merhaba, ben Mustafa. Astronomi ve Uzay Bilimleri 3.sinif ogrencisiydim ancak suan bolumume olan ilgimi kaybettigim icin zamanimin cogunu programlamaya ayiriyorum. Bu web sayfasiyla yaptigim projeleri gostermeye calisacagim
